spring.application.name=foodiesapi

#mongodb congfiguration
spring.data.mongodb.uri=${MONGODB_URI}
#aws s3 configuration
aws.access.key=${AWS_ACCESS_KEY}
aws.secret.key=${AWS_SECRET_KEY}
aws.region=${AWS_REGION}
aws.s3.bucketname=${AWS_BUCKET_NAME}
#jwt.secret.key=${JWT_SECRET}
jwt.secret.key=ThisIsMySuperSecretKeyForJwtAuthentication123456789
##razorpay configuration
razorpay.key.id=${RAZORPAY_KEY}
razorpay.key.secret=${RAZORPAY_SECRET}

