spring.application.name=foodiesapi
# =========================================================
# MONGODB
# =========================================================
spring.data.mongodb.uri=${MONGODB_URI}
# =========================================================
# AWS S3
# =========================================================
aws.access.key=${AWS_ACCESS_KEY}
aws.secret.key=${AWS_SECRET_KEY}
aws.region=${AWS_REGION}
aws.s3.bucketname=${AWS_BUCKET_NAME}
# =========================================================
# JWT
# =========================================================
jwt.secret.key=${JWT_SECRET}
# =========================================================
# RAZORPAY
# =========================================================
razorpay.key.id=${RAZORPAY_KEY}
razorpay.key.secret=${RAZORPAY_SECRET}
# =========================================================
# GEMINI AI
# =========================================================
spring.ai.openai.api-key=${GEMINI_API_KEY}
# =========================================================
# SERVER
# =========================================================
server.port=8080