spring.application.name=foodiesapi

#mongodb congfiguration
spring.mongodb.uri=mongodb://localhost:27017/foodies
#aws s3 configuration
aws.access.key=${AWS_ACCESS_KEY}
aws.secret.key=${AWS_SECRET_KEY}
aws.region=eu-north-1
aws.s3.bucketname=sn-foodies-storage-2026
#jwt.secret.key=${JWT_SECRET}
#
##razorpay configuration
#razorpay_key=${RAZORPAY_KEY}
#razorpay_secret=${RAZORPAY_SECRET}
